{% set name = "vector" %}
{% set version = "0.10.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/vector-{{ version }}.tar.gz
  sha256: b785678f449de32476f427911248391ddcc7c3582a522a88cbbd50c92dcae490

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - hatchling
    - hatch-vcs
  run:
    - numpy >=1.13.3
    - python >=3.6
    - importlib_metadata >=0.22
    - typing-extensions
    - packaging

test:
  imports:
    - vector
    - vector.backends
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/scikit-hep/vector
  summary: Vector classes and utilities
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Saransh-cpp
    - conda-forge/scikit-hep
