{% set name = "vector" %}
{% set version = "1.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/vector-{{ version }}.tar.gz
  sha256: 4fada4fddaa5c1bd69a5ba296ffd948cccb575ad7abe53d14960f56fe32dd4c1

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - hatchling
    - hatch-vcs
  run:
    - numpy >=1.14.5
    - python >=3.7
    - importlib_metadata >=0.22
    - typing-extensions
    - packaging

test:
  imports:
    - vector
    - vector.backends
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/scikit-hep/vector
  summary: Vector classes and utilities
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Saransh-cpp
    - conda-forge/scikit-hep
